%% Automatically generated, do not edit
%% Generated by gpb_compile version 3.21.0 on {{2019,8,12},{18,35,16}}

-ifndef(srv_sample_type).
-define(srv_sample_type, true).

-define(srv_sample_type_gpb_version, "3.21.0").

-ifndef('SRV.SAMPLE.TYPE.TYPE_PB_H').
-define('SRV.SAMPLE.TYPE.TYPE_PB_H', true).
-record('srv.sample.type.Type',
        {
        }).
-endif.

-endif.
