{application,srv,
             [{description,"An OTP application"},
              {vsn,"0.1.0"},
              {registered,[]},
              {mod,{srv_app,[]}},
              {applications,[kernel,stdlib]},
              {env,[]},
              {modules,[srv_app,srv_sample_func,srv_sample_type,srv_sup]},
              {maintainers,[]},
              {licenses,[]},
              {links,[]}]}.
